# Generated by Django 3.1.7 on 2021-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingocurrency",
            name="entry",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
