# Generated by Django 3.1.7 on 2021-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0002_auto_20210321_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingocurrency",
            name="entry",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="parkingocurrency",
            name="exit",
            field=models.DateTimeField(null=True),
        ),
    ]
