# Generated by Django 3.1.7 on 2021-03-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0003_auto_20210321_1530"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Park",
            new_name="Parking",
        ),
        migrations.AlterModelOptions(
            name="parking",
            options={"verbose_name": "Park"},
        ),
        migrations.AlterModelOptions(
            name="parkingocurrency",
            options={
                "verbose_name": "Parking Ocurrery",
                "verbose_name_plural": "Parking Ocurrencies",
            },
        ),
    ]
