image: python:latest

before_script:
  - pip install -r requirements.txt

test:
  before_script:
    - pip install -r requirements.txt
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test
lint:
  script:
    - black automobilies/
    - black parking/





