image: python:latest
stages:
  - test
  - lint

test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test
lint:
  stage: lint
  before_script:
    - pip install -r requirements.txt
  script:
    - black automobilies/
    - black parking/





