image: python:latest

variables:
    SECRET_KEY: ${SECRET_APP}
    DEBUG: "True"
    ALLOWED_HOSTS: "['*']"
    DB_ENGINE: "django.db.backends.sqlite3"
    DB_NAME: "test_database.sqlite3"
    ENVIROMENT: "test"

cache:
  paths:
- ~/.cache/pip/

before_script:
  - pip install -r requirements.txt

test:
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test
lint:
  script:
    - black automobilies/
    - black parking/





