image: python:latest
test:
  only:
    refs:
      -master

  before_script:
    - pip install -r requirements.txt
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test
lint:
  only:
    refs:
      -master
  before_script:
    - pip install -r requirements.txt
  script:
    - black automobilies/
    - black parking/





