# Generated by Django 3.1.7 on 2021-03-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automobilies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobilie",
            name="plate",
            field=models.CharField(max_length=8, verbose_name="Auto Plate"),
        ),
    ]
