# Generated by Django 3.1.7 on 2021-03-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automobilies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingOcurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automobilies.automobilie')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_ocurrencies', models.ManyToManyField(null=True, to='park.ParkingOcurrency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
